### ISSUE TITLE
Breaks on IE 11

### ISSUE THREAD

**Issue by livingston** [lukeed/obj-str#3]
**Bug**
IE 11 does not support `const` in `for` loops.

The `rollup` generated code has `const` instead of `var`.

**Fix**
The `rollup` build has to generate code using a transpiler like `babel`

**Comment by lukeed** [comment]
Hey, 

Odd, you shouldn't be getting any `const` anywhere 🤔 

These are the files sent to `npm`: https://github.com/lukeed/obj-str/tree/master/dist

And these are the `npm` entry modules: https://github.com/lukeed/obj-str/blob/master/package.json#L6-L7

Are you sure it's `obj-str`?

**Comment by lukeed** [comment]
Nevermind~! There wasn't a release after 0c3db18b5bd49670389a1bb67ccfc1db5ddc6151 🤦‍♂️ 

Fixed in `v1.0.1`. Thanks!
