### ISSUE TITLE
babel: can we avoid the leading space?

### ISSUE THREAD

**Issue by minushabens** [lukeed/obj-str#7]
Referring to this: https://github.com/lukeed/obj-str/tree/master/babel-plugin-optimize-obj-str#leading-space:

is there any way to delete that space?

Can we avoid that space at all? I mean, we have all the time at compile time, nope?

**Comment by lukeed** [comment]
Hi there,

It you look at the implementation PR (#6) you'll see that it originally was an option. However, as you can see in that discussion, the output this plugin produced to avoid a leading space was far more verbose & expensive to run.

This plugin can only make the optimizations you're thinking of if everything is known/static at compile time, which isn't likely -- and if it is, then you didn't need to be using `obj-str` in that instance.

Because of this, we removed the option to avoid the possibility of giving you a transform bigger than `obj-str` itself... that'd be silly.

Hope that helps!

**Comment by minushabens** [comment]
> the output this plugin produced to avoid a leading space was far more verbose & expensive to run

I used [this to calculate your examples](https://perf.link/#eyJpZCI6ImoxcjljNmJhaDgyIiwidGl0bGUiOiIiLCJiZWZvcmUiOiJpbXBvcnQgb2Jqc3RyIGZyb20gXCJodHRwczovL3VucGtnLmNvbS9vYmotc3RyP21vZHVsZVwiIiwidGVzdHMiOlt7Im5hbWUiOiIiLCJjb2RlIjoibGV0IF87XG5cIlwiICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPSB0cnVlLCAnJykgKyBcImFiY2RcIiA6IFwiXCIpICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPyAnICcgOiAoXyA9IHRydWUsICcnKSkgKyBcImVmZ2hpamtsXCIgOiBcIlwiKSArXG4gIChNYXRoLnJhbmRvbSgpIDw9IDAuNSA%2FIChfID8gJyAnIDogKF8gPSB0cnVlLCAnJykpICsgXCJtbm9wcXJzdHV2d3h5elwiIDogXCJcIikgK1xuICAoTWF0aC5yYW5kb20oKSA8PSAwLjUgPyAoXyA%2FICcgJyA6IChfID0gdHJ1ZSwgJycpKSArIFwiZWZnaGlqa2xtbm9wcXJzdHV2d3h5elwiIDogXCJcIikgK1xuICAoTWF0aC5yYW5kb20oKSA8PSAwLjUgPyAoXyA%2FICcgJyA6IChfID0gdHJ1ZSwgJycpKSArIFwiYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpcIiA6IFwiXCIpOyIsInJ1bnMiOlsxNzM1MDAwLDcwNzAwMCwxNzM1MDAwLDE4NjMwMDAsNDE3MDAwLDc3NTAwMCw4NzAwMDAsMjgwMDAwLDUxMDAwMCwxMTU2MDAwLDExNzAwMDAsMTQ3MDAwMCwxMTI0MDAwLDE3NzYwMDAsMTI3MDAwLDk3NDAwMCw3NzAwMCw1MDAwLDEyMTAwMCw0MjQwMDAsODM0MDAwLDgwMDAwLDEzNDkwMDAsODU3MDAwLDQwMDAsMjc0MDAwLDQxMDAwLDUzMTAwMCwxMTMwMDAwLDE0NzcwMDAsNjcyMDAwLDE5ODQwMDAsNDIwMDAsMzExMDAwLDU2MjAwMCw0NTIwMDAsMTkxODAwMCwzMDAwMCwxOTEzMDAwLDYwMTAwMCw5NDAwMDAsMTAwMDAwMCw3NTYwMDAsMjA1MDAwLDkwNjAwMCw0MzAwMDAsMzMwMDAsMjAwMCwxNjUyMDAwLDIxMzAwMCwzNjEwMDAsOTUyMDAwLDE5MDAwMCwxNzMwMDAsMzk3MDAwLDU1MDAwLDgyMTAwMCwxMDM4MDAwLDYxODAwMCw3MTkwMDAsNjAyMDAwLDIwNjEwMDAsMzA0MDAwLDE3NjMwMDAsNDg3MDAwLDE0NjYwMDAsNzk0MDAwLDg2NjAwMCwxNzEwMDAsMTY5MjAwMCw2MTAwMDAsMTI3NTAwMCwxNDU4MDAwLDgxMDAwMCw2ODcwMDAsNzAwMCwxMzA2MDAwLDgwNjAwMCwyMTQwMDAsODEwMDAwLDE4MzkwMDAsODk2MDAwLDEyNTgwMDAsMTM5MTAwMCwxOTY4MDAwLDk0NDAwMCw0MTIwMDAsMTU4OTAwMCwxOTgzMDAwLDM2MzAwMCw1NTEwMDAsNzAwMCwxMTEwMDAwLDExOTEwMDAsMTI3MjAwMCw0OTUwMDAsMTEwODAwMCwxMjg5MDAwLDE4ODcwMDAsMzE3MDAwXSwib3BzIjo4Mzg5ODB9LHsibmFtZSI6IiIsImNvZGUiOiJvYmpzdHIoe1xuICBhYmNkOiBNYXRoLnJhbmRvbSgpIDw9IDAuNSxcbiAgZWZnaGlqa2w6IE1hdGgucmFuZG9tKCkgPD0gMC41LFxuICBtbm9wcXJzdHV2d3h5ejogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG4gIGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo6IE1hdGgucmFuZG9tKCkgPD0gMC41LFxuICBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG59KTsiLCJydW5zIjpbNTMzMDAwLDMzMDAwMCw5NTYwMDAsNzUwMDAsMjI4MDAwLDg3NTAwMCw3OTcwMDAsNDQwMDAwLDgwOTAwMCw3MDkwMDAsNzgxMDAwLDkwMDAwMCw3ODMwMDAsMTIyMDAwMCwzMDMwMDAsMTkwMDAwLDExNDkwMDAsNjU1MDAwLDg4NjAwMCwzMTAwMDAsMTAwNzAwMCw3MzUwMDAsMjQyMDAwLDExMDQwMDAsNjc4MDAwLDI5MzAwMCwxMDI0MDAwLDc1MDAwLDYxMjAwMCwxMDAwLDEzOTAwMCwzMDUwMDAsMzgzMDAwLDU1NzAwMCwyMjAwMDAsMzkzMDAwLDM4NTAwMCw4MjUwMDAsMzIwMDAsNDMwMDAsNzgxMDAwLDE1MzAwMCwyMzYwMDAsMTIyOTAwMCwzMjcwMDAsMTE2MTAwMCwxMDQ5MDAwLDkzNjAwMCwzOTMwMDAsOTk5MDAwLDYwNjAwMCw3MTQwMDAsMTA2NDAwMCwxMDAwLDk0MDAwMCw1MDcwMDAsNDQ5MDAwLDY1OTAwMCw4NjkwMDAsMTE4MDAwLDEwMjcwMDAsMTEyNzAwMCwxMzYwMDAsMTY4MDAwLDUzMDAwMCw3NjAwMDAsNDE2MDAwLDExMzYwMDAsMTAwMCwxMTQyMDAwLDc5NDAwMCw5MzkwMDAsNDk0MDAwLDcwODAwMCw3ODYwMDAsOTAzMDAwLDc5NzAwMCwxODMwMDAsMTYyMDAwLDIwMDAwLDExNDQwMDAsOTcwMDAsMTAwMCw5NDAwMDAsNTEwMDAwLDU2ODAwMCw4MDgwMDAsNzE3MDAwLDg2ODAwMCwzMTAwMDAsMjQwMDAsMTAwMCwxMzkwMDAsMTA2NTAwMCwxMTE0MDAwLDgyODAwMCw5NzMwMDAsODE0MDAwLDg2NDAwMCw1MDUwMDBdLCJvcHMiOjU5NjkyMH0seyJuYW1lIjoiIiwiY29kZSI6ImxldCBfO1xuXCJcIiArXG4gIChNYXRoLnJhbmRvbSgpIDw9IDAuNSA%2FIChfID0gdHJ1ZSwgJycpICsgXCJhYmNkXCIgOiBcIlwiKSArXG4gIChNYXRoLnJhbmRvbSgpIDw9IDAuNSA%2FIChfID8gJyAnIDogKF8gPSB0cnVlLCAnJykpICsgXCJlZmdoaWprbFwiIDogXCJcIikgK1xuICAoTWF0aC5yYW5kb20oKSA8PSAwLjUgPyAoXyA%2FICcgJyA6IChfID0gdHJ1ZSwgJycpKSArIFwibW5vcHFyc3R1dnd4eXpcIiA6IFwiXCIpICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPyAnICcgOiAoXyA9IHRydWUsICcnKSkgKyBcImVmZ2hpamtsbW5vcHFyc3R1dnd4eXpcIiA6IFwiXCIpICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPyAnICcgOiAoXyA9IHRydWUsICcnKSkgKyBcImFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6XCIgOiBcIlwiKSArXG4gIChNYXRoLnJhbmRvbSgpIDw9IDAuNSA%2FIChfID8gJyAnIDogKF8gPSB0cnVlLCAnJykpICsgXCJhYmNkXCIgOiBcIlwiKSArXG4gIChNYXRoLnJhbmRvbSgpIDw9IDAuNSA%2FIChfID8gJyAnIDogKF8gPSB0cnVlLCAnJykpICsgXCJlZmdoaWprbFwiIDogXCJcIikgK1xuICAoTWF0aC5yYW5kb20oKSA8PSAwLjUgPyAoXyA%2FICcgJyA6IChfID0gdHJ1ZSwgJycpKSArIFwibW5vcHFyc3R1dnd4eXpcIiA6IFwiXCIpICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPyAnICcgOiAoXyA9IHRydWUsICcnKSkgKyBcImVmZ2hpamtsbW5vcHFyc3R1dnd4eXpcIiA6IFwiXCIpICtcbiAgKE1hdGgucmFuZG9tKCkgPD0gMC41ID8gKF8gPyAnICcgOiAoXyA9IHRydWUsICcnKSkgKyBcImFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6XCIgOiBcIlwiKTsiLCJydW5zIjpbMTg5MDAwLDU2MjAwMCwyMzAwMCw2ODUwMDAsOTU4MDAwLDkxMTAwMCwzMzIwMDAsOTQwMDAwLDg4MzAwMCwxNjMwMDAsNjM1MDAwLDExNjAwMCw4NTAwMCw0OTgwMDAsNTU4MDAwLDEyMDIwMDAsNzk3MDAwLDUyOTAwMCwyNzEwMDAsNTM3MDAwLDExNDYwMDAsMzg3MDAwLDg4NDAwMCwzNTMwMDAsNjcyMDAwLDIzOTAwMCwxNTUwMDAsOTgwMDAwLDk2OTAwMCwxMTEwMDAsMjYzMDAwLDE4MDAwLDUzMDAwMCw5OTcwMDAsODgyMDAwLDgxODAwMCw3MzgwMDAsOTQ2MDAwLDEwMTAwMCwxMDgxMDAwLDEyMjkwMDAsMTEyNjAwMCw5MDgwMDAsMzc0MDAwLDY5NzAwMCwzMDAwLDgwMjAwMCw3MzAwMDAsNTA4MDAwLDgyMDAwMCw0MzgwMDAsMjkxMDAwLDEwMDcwMDAsOTM2MDAwLDQ1NDAwMCwxMDQ2MDAwLDUzMjAwMCw2NzIwMDAsNjA5MDAwLDM4NDAwMCwzMzAwMCw1ODIwMDAsNTA0MDAwLDU3NzAwMCw4NzIwMDAsODk1MDAwLDgxMDAwMCw3MDkwMDAsMTE3ODAwMCw2NTAwMCwxMDM5MDAwLDEwNTkwMDAsNjMxMDAwLDgwOTAwMCw3MDkwMDAsNTE0MDAwLDMyNTAwMCwxMjM3MDAwLDY0ODAwMCw0NzAwMDAsMTExMjAwMCw0NDcwMDAsMTAxOTAwMCw3MzQwMDAsMTEwMTAwMCw0MDcwMDAsNjE3MDAwLDQ5ODAwMCw1OTQwMDAsOTgwMDAwLDI1OTAwMCw1NDcwMDAsODUyMDAwLDM0MjAwMCwxMDY4MDAwLDExMzcwMDAsMTgyMDAwLDEyMTAwMDAsNTkwMDAsNjA2MDAwXSwib3BzIjo2NDE0NzB9LHsibmFtZSI6IiIsImNvZGUiOiJvYmpzdHIoe1xuICBhYmNkOiBNYXRoLnJhbmRvbSgpIDw9IDAuNSxcbiAgZWZnaGlqa2w6IE1hdGgucmFuZG9tKCkgPD0gMC41LFxuICBtbm9wcXJzdHV2d3h5ejogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG4gIGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo6IE1hdGgucmFuZG9tKCkgPD0gMC41LFxuICBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG4gIGFiY2Q6IE1hdGgucmFuZG9tKCkgPD0gMC41LFxuICBlZmdoaWprbDogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG4gIG1ub3BxcnN0dXZ3eHl6OiBNYXRoLnJhbmRvbSgpIDw9IDAuNSxcbiAgZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejogTWF0aC5yYW5kb20oKSA8PSAwLjUsXG4gIGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6OiBNYXRoLnJhbmRvbSgpIDw9IDAuNSxcbn0pOyIsInJ1bnMiOls1MzMwMDAsNjg5MDAwLDI5MDAwLDY4NDAwMCw2ODIwMDAsMzg3MDAwLDM4ODAwMCw2MjMwMDAsNjkyMDAwLDk4MDAwLDIyMDAwLDI1MjAwMCw2OTQwMDAsMTAwMCw0MjQwMDAsMzUyMDAwLDQ0MzAwMCwzMTcwMDAsMTAwMCw1NTAwMCw0MzQwMDAsMjg3MDAwLDQwMTAwMCwxODAwMDAsNjg0MDAwLDU0MDAwLDUwMDAsNTc2MDAwLDUzNDAwMCwyMzAwMDAsNjM5MDAwLDU4MzAwMCwzMDAwLDU0NTAwMCwzOTYwMDAsOTMwMDAsMTYwMDAwLDMyMjAwMCw2ODUwMDAsNDczMDAwLDYwNzAwMCwxMzAwMCwzMjAwMDAsMTAwMCwyODgwMDAsMjIwMDAsNjA5MDAwLDUxMDAwMCwzNzEwMDAsNjU3MDAwLDMxNzAwMCwzNjAwMCw2ODkwMDAsNjg0MDAwLDIwMDAwMCw0NTkwMDAsMTQ4MDAwLDI0NzAwMCwxMjAwMCwyOTgwMDAsNTAyMDAwLDY3OTAwMCw2NDcwMDAsMjI4MDAwLDUzNTAwMCwyMDkwMDAsNjkzMDAwLDU2NDAwMCw2ODcwMDAsNjg2MDAwLDY5MzAwMCwxNjAwMCwxNjkwMDAsNDMxMDAwLDM3NzAwMCw3MzAwMCwxMjkwMDAsMTczMDAwLDU3MDAwLDM4NzAwMCwxOTEwMDAsNjAwMCw2OTMwMDAsMzgwMDAwLDY4NTAwMCw1MjUwMDAsNDQ0MDAwLDE1NzAwMCw0OTUwMDAsMjYwMDAsMzg2MDAwLDY0MTAwMCwyODMwMDAsNjkzMDAwLDYzNDAwMCw2OTAwMCw2OTAwMDAsMTExMDAwLDQwMzAwMCw1MDgwMDBdLCJvcHMiOjM3MDkzMH1dLCJ1cGRhdGVkIjoiMjAyMS0wMy0yNlQxMToyMzozOS41NzFaIn0%3D).

As you can see the results are also excellent in the case of many replacements.

And about [this comment](https://github.com/lukeed/obj-str/pull/6#issuecomment-778345105):

> maybe should mention the inflection point where this plug-in is no longer worth it. In this sample, another 2-3 replacements of similar complexity completely outweighs just using obj-str directly. (I know leadingSpace:true buys a bigger headstart)

What do you mean with `completely outweighs`? Size? Speed?

For the size side, maybe as @alanorozco said `terser` and similar can help us.

For the speed I think that in both cases (leading space or not) it is a winning solution for both a few classes and many (as that bench shows).

We would like to use it extensively in small components (Vue, React, Preact) rendered many times even hundreds all together and we're trying to understand how to best measure.

What do you think?

**Comment by lukeed** [comment]
> What do you mean with completely outweighs? Size? Speed?

Size. It relates to the first point too. After a few replacements, the new code is the same size (or larger) than `obj-str`'s original size. All replacements are inline & cannot share runtime code, which means this is linear growth. Terser doesn't help here either for the same reasoning -- all it can do is lower the size-cost of each replacement so that it takes more of them to hit that "inflection point". The output was already very small, so at best, this would allow "2-3" to be "3-5"

If you're looking for speed, use the current transform. A leading space is not worth the (slight) perf loss and added runtime code. That's why it was removed.

**Comment by alanorozco** [comment]
> For the size side, maybe as @alanorozco said terser and similar can help us.

To clarify, the previous point about terser was related to constant expressions, not leading spaces. (We ended up evaluating expressions like terser would.)

I agree with @lukeed regarding size of expressions with optional leading spaces.
